version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    restart: on-failure
    volumes:
      - /app/node_modules
      - .:/app
